### ISSUE TITLE
When I run train.py ,I met this problem:

### ISSUE THREAD

**Issue by Nireil** [edwardzhou130/Panoptic-PolarNet#5]
{'model_name': 'Panoptic_PolarNet', 'dataset': {'name': 'semantickitti', 'path': 'data', 'output_path': 'out/SemKITTI', 'instance_pkl_path': 'data', 'rotate_aug': True, 'flip_aug': True, 'inst_aug': True, 'inst_aug_type': {'inst_os': True, 'inst_loc_aug': True, 'inst_global_aug': True}, 'gt_generator': {'sigma': 5}, 'grid_size': [480, 360, 32]}, 'model': {'model_save_path': './Panoptic_SemKITTI.pt', 'pretrained_model': 'empty', 'polar': True, 'visibility': True, 'train_batch_size': 2, 'val_batch_size': 2, 'test_batch_size': 1, 'check_iter': 4000, 'max_epoch': 100, 'post_proc': {'threshold': 0.1, 'nms_kernel': 5, 'top_k': 100}, 'center_loss': 'MSE', 'offset_loss': 'L1', 'center_loss_weight': 100, 'offset_loss_weight': 10, 'enable_SAP': True, 'SAP': {'start_epoch': 30, 'rate': 0.01}}}
Using MSE for heatmap regression, weight: 100
Using L1 for offset regression, weight: 10
[PANOPTIC EVAL] IGNORE:  [0]
[PANOPTIC EVAL] INCLUDE:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
  0%|                                                  | 0/9565 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/data/p202008021038/Panoptic-PolarNet-main/train.py", line 236, in <module>
    main(args)
  File "/data/p202008021038/Panoptic-PolarNet-main/train.py", line 106, in main
    for i_iter,(train_vox_fea,train_label_tensor,train_gt_center,train_gt_offset,train_grid,_,_,train_pt_fea) in enumerate(train_dataset_loader):
  File "/data/p202008021038/anaconda3/envs/ppnet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/data/p202008021038/anaconda3/envs/ppnet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/data/p202008021038/anaconda3/envs/ppnet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/data/p202008021038/anaconda3/envs/ppnet/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data/p202008021038/anaconda3/envs/ppnet/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/data/p202008021038/anaconda3/envs/ppnet/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/p202008021038/anaconda3/envs/ppnet/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/p202008021038/Panoptic-PolarNet-main/dataloader/dataset.py", line 313, in __getitem__
    xyz,labels,insts,feat = self.inst_aug.instance_aug(xyz,labels.squeeze(),insts.squeeze(),feat)
  File "/data/p202008021038/Panoptic-PolarNet-main/dataloader/instance_augmentation.py", line 40, in instance_aug
    random_choice = np.random.choice(len(self.instance_path[self.thing_list[n]]),count)
  File "mtrand.pyx", line 903, in numpy.random.mtrand.RandomState.choice
ValueError: a must be greater than 0 unless no samples are taken

  0%|                                                  | 0/9565 [00:00<?, ?it/s]

进程已结束，退出代码为 1

**Comment by zzh-ecnu** [comment]
It looks like dataset or env. problems.
1. check your datasets, ensure they are downloaded rightly.
2. check your depency's version, according to your error information, i suggest you **switch the numpy version in proper range**.

**Comment by yinpub** [comment]
我也是这个问题

**Comment by yinpub** [comment]
是windows的问题.没读到数据的路径》
